//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovedCo
    {
        public int appCos_id { get; set; }
        public Nullable<int> cosmetic_license_num { get; set; }
        public string cosmetic_businessName { get; set; }
        public string cosmetic_address { get; set; }
        public string cosmetic_city { get; set; }
    }
}
