//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppUser()
        {
            this.SkinPlans = new HashSet<SkinPlan>();
        }
    
        public int appUser_id { get; set; }
        public string username { get; set; }
        public string user_password { get; set; }
        public string user_firstName { get; set; }
        public string user_lastName { get; set; }
        public string user_email { get; set; }
        public string user_gender { get; set; }
        public Nullable<System.DateTime> user_birth { get; set; }
        public byte[] user_profilepic { get; set; }
        public byte[] user_picsprocess { get; set; }
        public string user_role { get; set; }
        public string user_skinType { get; set; }
        public string user_skinProblem { get; set; }
        public string user_cheek { get; set; }
        public string user_Tzone { get; set; }
        public string user_sunExposure { get; set; }
        public string user_stress { get; set; }
        public string user_period { get; set; }
        public string user_dermatology { get; set; }
        public string user_currentProducts { get; set; }
        public string user_sensitive { get; set; }
        public string user_areas { get; set; }
        public Nullable<int> cosmetic_license_num { get; set; }
        public string cosmetic_businessName { get; set; }
        public string cosmetic_address { get; set; }
        public string cosmetic_city { get; set; }
        public string cosmetic_speciality { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkinPlan> SkinPlans { get; set; }
    }
}
