//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoPlans
    {
        public int autoplan_id { get; set; }
        public string autoplan_name { get; set; }
        public string autoplan_skinType { get; set; }
        public string product_id { get; set; }
        public string autoplan_manual { get; set; }
    }
}
