//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bgroup90SkinMe : DbContext
    {
        public bgroup90SkinMe()
            : base("name=bgroup90SkinMe")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppCosmetologists> AppCosmetologists { get; set; }
        public virtual DbSet<AppUsers> AppUsers { get; set; }
        public virtual DbSet<AutoPlans> AutoPlans { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<SkinPlan> SkinPlan { get; set; }
    }
}
