//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
<<<<<<<< HEAD:WebApi/DATA/Model2.Context.cs
    public partial class bgroup90_prodEntities1 : DbContext
    {
        public bgroup90_prodEntities1()
            : base("name=bgroup90_prodEntities1")
========
    public partial class DbSkinme : DbContext
    {
        public DbSkinme()
            : base("name=DbSkinme")
>>>>>>>> 88ae5c32b790f8802018c264c34d7e974a2cfb60:WebApi/DATA/ModelSkinme.Context.cs
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppCosmetologist> AppCosmetologists { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductsForPlan> ProductsForPlans { get; set; }
        public virtual DbSet<ProductsForProfile> ProductsForProfiles { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<SkinPlan> SkinPlans { get; set; }
        public virtual DbSet<UsersImage> UsersImages { get; set; }
    }
}
