//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bgroup90_test2Entities : DbContext
    {
        public bgroup90_test2Entities()
            : base("name=bgroup90_test2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppCosmetologist> AppCosmetologists { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<AutoPlan> AutoPlans { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Products_for_plan> Products_for_plan { get; set; }
        public virtual DbSet<ProductsForProfile> ProductsForProfiles { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<SkinPlan> SkinPlans { get; set; }
    }
}
