//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsForProfiles
    {
        public int pfp_id { get; set; }
        public Nullable<int> profile_code { get; set; }
        public Nullable<int> prod_id { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Profiles Profiles { get; set; }
    }
}
